name: 'Marcus Berry - Voiceover '
favicon: null
layout_spectrum: 0.6813045882154256
typography_spectrum: 0.3247717844787985
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6768447724170983
  lightness: 0.8801827696152031
  saturation: 0.5850007354747504
  rhythmicContrast: 0.7942797802388668
purpose: []
